@url = 192.168.1.116:5000
@token = test_secret

###
//Retrieve all machine vitals
GET http://{{url}}/status
API_KEY: {{token}}

###
//send a command like X0 Z1 Y10
POST http://{{url}}/send_command
API_KEY: {{token}}
Content-Type: application/json

{
	"mdi_command": "X10 Z10"
}

###
//Commands are a toggle
//power, estop
POST http://{{url}}/set_machine_status
API_KEY: {{token}}
Content-Type: application/json

{
	"command": "estop"
}

###
POST http://{{url}}/manual
API_KEY: {{token}}
Content-Type: application/json

{
	"axes": 2,
	"speed": -1,
	"increment": 1
}

###
GET http://{{url}}/return_files
API_KEY: {{token}}


###
//Commands are
//home and unhome
POST http://{{url}}/set_home
Content-Type: application/json
API_KEY: {{token}}

{
    "command": "home"
}

###
//Commands are
//start, pause, resume, stop
POST http://{{url}}/control_program
Content-Type: application/json
API_KEY: {{token}}

{
    "command": "stop"
}

###
//Commands are
//spindle_forward, spindle_reverse, spindle_off, spindle_increase, spindle_decrease, spindle_constant
POST http://{{url}}/spindle
Content-Type: application/json
API_KEY: {{token}}

{
	"command": {
		"spindle_direction": "spindle_forward"
	}
}

###
//Give a velocity in mm min
POST http://{{url}}/maxvel
Content-Type: application/json
API_KEY: {{token}}

{
	"velocity": 1600
}

###
//Set feedrate in decimal 0-1.2
POST http://{{url}}/feed
Content-Type: application/json
API_KEY: {{token}}

{
	"feedrate": 1.1
}

###
//Set the path to the file
POST http://{{url}}/open_file
Content-Type: application/json
API_KEY: {{token}}

{
	"path": "/home/machinekit/devel/webUI/files/smile.nc"
}

###
//Set the path to the file
GET http://{{url}}/tool_change
API_KEY: {{token}}