@url = 192.168.1.116:5000
@token = test_secret


###
POST http://{{url}}/machinekit/spindle/direction
API_KEY: {{token}}
Content-Type: application/json

{
    "spindle_direction": "spindle_forward"
}


###
POST http://{{url}}/machinekit/spindle/enabled
API_KEY: {{token}}
Content-Type: application/json

{
    "spindle_enabled": "spindle_off"
}

###
POST http://{{url}}/machinekit/spindle/speed
API_KEY: {{token}}
Content-Type: application/json

{
    "spindle_speed": "spindle_decrease"
}

###
POST http://{{url}}/machinekit/spindle/override
API_KEY: {{token}}
Content-Type: application/json

{
    "spindle_override": 1
}

###
POST http://{{url}}/machinekit/spindle/brake
API_KEY: {{token}}
Content-Type: application/json

{
    "spindle_brake": "brake_engaged"
}